version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  target-branch: "dev"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
#  ignore:
#    - dependency-name: cn.hutool:hutool-all
#      versions:
#      - 5.6.0
